[package]
name = "mun_codegen_macros"
version = "0.1.0"
authors = ["The Mun Team <team@mun-lang.org>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"
